### PR TITLE
adds author field to items of rss feed

### PR DESCRIPTION
**Pull request by cosenal**
This is a fix for #5 

Use case: when I am reading ownCloud news feed with ownCloud News :-P, I really want to know who authored the post!

### CODE REVIEW

**Comment by cosenal** [comment]
@karlitschek @tomneedham I don't know if you guys get notifications from this repo.

**Comment by tomneedham** [comment]
Hey thanks @cosenal! We don't actually have contribook setup on the staging server and this is something we should definitely look into so we can properly test these things. Code looks ok, but I don't know masses about it. @karlitschek Is probably better to comment.

**Comment by karlitschek** [comment]
cool! Thanks

**Comment by karlitschek** [comment]
Will update the website at the next opportunity :-)

**Pull request merged**
